services:
  - type: web
    name: pdf-decrypt-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
